Introduction to Python
================================

Lesson 2 - Part1
--------

## Summary

In this Lesson we will start using Python in order to create some models.

The models that we will create are:
  - Linear

In order to do so we must intruduce some important libraries:

  - Pandas
  - Sklearn
  - Numpy

In [6]:
%load_ext rpy2.ipython

## Numpy

Citing from the [Numpy Website](http://www.numpy.org/): NumPy is the fundamental package for scientific computing with Python. It contains among other things:
  - a powerful N-dimensional array object
  - sophisticated (broadcasting) functions
  - tools for integrating C/C++ and Fortran code
  - useful linear algebra, Fourier transform, and random number capabilities
For the moment our focus is on the first point, in oder to start usign proper arrays.

In [1]:
import numpy as np
#Creation of an array
ar1=np.array([1,2,3])
print('type di ar1',type(ar1))
ar1

type di ar1 <class 'numpy.ndarray'>


array([1, 2, 3])

Note the difference between this new object and the standard Python list:

In [2]:
classList = [1,2,3]
print('Type of classList:',type(classList))
print(ar1,classList)

Type of classList: <class 'list'>
[1 2 3] [1, 2, 3]


In [3]:
#Use shape to see the dimension of ar1
print('Dimension of ar1 are:',ar1.shape)
try:
    print('Using .shape()')
    print(ar1,ar1.shape())
except Exception as e:
    print('ERROR:',e)
    print('You must use .shape without brackets')
    print(ar1,ar1.shape)

Dimension of ar1 are: (3,)
Using .shape()
ERROR: 'tuple' object is not callable
You must use .shape without brackets
[1 2 3] (3,)


Why we have to use `shape`? We can't use `len`?

In [4]:
len(ar1)

3

In [8]:
#Creation of a multimensional array
ar2=np.array([[1,2,3],[4,5,6]])#,dtype=complex
print('Shape di ar2',ar2.shape)
print(ar2)
len(ar2)
print(type(ar2))

Shape di ar2 (2, 3)
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## Comparison with R array

Numpy array are very similar to `R` array:

In [7]:
%%R

arR1 = array(c(1,2,3,4,5,6),c(2,3))
arR1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


**NOTE**: array and matrix in nupy are different objects

In [9]:
#Creatiomn of a matrix
mt=np.mat('1 2;3 4')
print(type(mt))
print(mt)

<class 'numpy.matrix'>
[[1 2]
 [3 4]]


In [10]:
#Putting the matrix inside an array
ar3=np.array([np.mat('1 2; 3 4'),np.mat('4 5; 6 7')])
print(type(ar3))
print(ar3)

<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [11]:
#In order to keep the correct type
ar3=np.array(np.mat('1 2; 3 4'), subok=True)
print(type(ar3))
print(ar3)
#ar3
# mt

<class 'numpy.matrix'>
[[1 2]
 [3 4]]


How do I select elements inside an array?

In [17]:
print(ar2)
print('-------')
#The same way we do with list
print(ar2[1])
print(type(ar2[1]))
#To access a singl element
ar2[1,2]

[[1 2 3]
 [4 5 6]]
-------
[4 5 6]
<class 'numpy.ndarray'>


6

**NOTE**: as we have seen in the previos lesson, also with `np.array` we have to use `.copy()`.

Without `.copy()` we'll create a pointer to the original array.

In [20]:
print(ar2)
ar2_bis=ar2.copy()
ar2_bis[1,]=[0,0,0]
#What'll be the result of this operation?
print(ar2)
#ar2_bis
print(ar2_bis)

[[1 2 3]
 [1 1 1]]
[[1 2 3]
 [1 1 1]]
[[1 2 3]
 [0 0 0]]


## Other properties of np.array

Just to mention some other features, we can look to append:

In [21]:
ap1=np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])
print(ap1,type(ap1))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [22]:
#Please note that the result is flattened
ap2=np.append([[1, 2, 3]], [[4, 5, 6], [7, 8, 9]], axis=0)
print(ap2,type(ap2))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [23]:
ap3=np.append([[1, 2, 3],[1,1,1]], [[4, 5, 6], [7, 8, 9]], axis=1)
print(ap3,type(ap3))

[[1 2 3 4 5 6]
 [1 1 1 7 8 9]] <class 'numpy.ndarray'>


## Exercise Numpy

Create an array of 3 row and 2 columns.

Add a row of 0.

Add to each row ['a','b'].

In [26]:
a=np.array([[1,2],[4,5],[6,7]])
print(a)
np.append(a,[[0,0]],axis=0)
np.append(a,[['a','b'],['a','b'],['a','b']],axis=1)

[[1 2]
 [4 5]
 [6 7]]


array([['1', '2', 'a', 'b'],
       ['4', '5', 'a', 'b'],
       ['6', '7', 'a', 'b']], dtype='<U21')

## Comparison between array an list

Let's understand why for big data it's important to use an array istead of a list.

We are going to do the sum of the list and two array. In one case is the sum of number, in the other the sum between two arrays like in linear algebra.

In [27]:
a=[i for i in range(0,10000)]
%timeit -n 100 s=a+a
b=np.array([i for i in range(0,10000)])
%timeit -n 100 s2=b+b

56.7 µs ± 5.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
9.15 µs ± 3.56 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
%%R
c=as.integer(seq(1,10))
print(class(c))
d=data.frame(c)
print(class(d))


[1] "integer"
[1] "data.frame"


In [29]:
%%timeit -n 100
%R c+c

2.52 ms ± 375 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [30]:
%%timeit -n 100
%R d+d

3.3 ms ± 323 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Pandas 

Citing the [Pandas Website](https://pandas.pydata.org/): *pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language*.

What interest us the most is the possibility of create and use, like in R, **dataframes** ([Pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)).

In [31]:
import pandas as pd

#Creation of a dataframe
df=pd.DataFrame({'a':[1,2,3],'b':[4,5,6]})
print(df,'\n',type(df))

   a  b
0  1  4
1  2  5
2  3  6 
 <class 'pandas.core.frame.DataFrame'>


Remembering previous lessons, can you tell what we have just done?
How can We generalize the previous expression?

In [33]:
#We can create a dataframe also using another syntax
df1_bis = pd.DataFrame([[10,20,30],[11,21,31],[1,2,3]],columns=['ten','twenty','thirty'])
print(df1_bis)

   ten  twenty  thirty
0   10      20      30
1   11      21      31
2    1       2       3


In [34]:
print('We can add columns afterward')
df['c']=[0,0,0]
print(df)

We can add columns afterward
   a  b  c
0  1  4  0
1  2  5  0
2  3  6  0


In [35]:
#Creation of a dataframe with index
df2 = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
                  index=['cobra', 'viper', 'sidewinder'],
                  columns=['max_speed', 'shield'])
print(df2)
print(type(df2))

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
<class 'pandas.core.frame.DataFrame'>


In [36]:
df3=pd.DataFrame({'col1':[10,20,30],'col2':['y','z','k']},index=['a','b','c'])
df3

col1 col2
a    10    y
b    20    z
c    30    k

**NOTE**: a dataframe can be created also starting from a `np.array` simply using `pd.DataFrame`.

In [38]:
print(type(ap2))
dfFromArray=pd.DataFrame(ap2,columns=['pippo','pluto','paperino'])#,columns=['pippo','pluto','paperino'])
print(ap2)
dfFromArray


<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


pippo  pluto  paperino
0      1      2         3
1      4      5         6
2      7      8         9

In [45]:
df2

max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

## Properties of a dataframe

In the followig cell there is a sample of attributes ad properties of a pandas dataframe.

Some of them are:

  - `index`
  - `values`
  - `max()`
  - `add()`

In [42]:
%qtconsole
print(df)
df.index
df.values
df.columns
df.max()
df.min()
df.mean()
df.median()
df.add(df)
#se the link above

   a  b  c
0  1  4  0
1  2  5  0
2  3  6  0


a   b  c
0  2   8  0
1  4  10  0
2  6  12  0

In [63]:
print(df)
df


   a  b  c
0  1  4  0
1  2  5  0
2  3  6  0


a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

## Display dataframes nicely

In order to print a dataframe in a nice way, like it is visualized without print if it is at the of a cell, we can use `display` from the library `IPython.display`.

It is also possible to convert a dataframe to html with `to_html`, from the same library, and then use display.

**NOTE**: display can also print text before and after an object, just like `print`.

In [64]:
from IPython.display import display, HTML
display(df)

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

In [ ]:
#Alternative
print('using .to_html()')
display(HTML(df.to_html()))

In [66]:
print('Display can also print text')
display('Some random text',df)

Display can also print text


'Some random text'

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

## How to select row and columns

Let's dive a little bit more in some dataframes property.

Important functions for selecting dataframe's elements are:
  - `index` 
  - `loc`
  - `iloc`
 
The difference between `loc` and `iloc` is subtle:
  - `loc` allow to select elemets by **name**
  - `iloc` allow to select elemets by **position**

It always possible to select columns by name with `[[]]`.

In [68]:
#Creation of a dataframe without an index
dfCity=pd.DataFrame({'val1':[10,20,30],'val2':[-1,-2,-3],'city':['Roma','Milano','Napoli']})
print('dfCity before the cration of the index')
display(dfCity)
dfCity.index

dfCity before the cration of the index


val1  val2    city
0    10    -1    Roma
1    20    -2  Milano
2    30    -3  Napoli

RangeIndex(start=0, stop=3, step=1)

In [70]:
#Selecting one column as index
dfCity.set_index('city',inplace=True)#inplace
display(dfCity)

val1  val2
city              
Roma      10    -1
Milano    20    -2
Napoli    30    -3

### WARNING #1
From now on, we must take care on the parameter `inplace` when we use multiple functions over a dataframe

In [71]:
#Selecting column by name
display(df)
print('Selection of a column by name')
display(df[['a']])

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

Selection of a column by name


a
0  1
1  2
2  3

In [75]:
print('Selectig a column using loc')
display(df.loc[:,'b'])

Selectig a column using loc


0    4
1    5
2    6
Name: b, dtype: int64

In [ ]:
print('Selectig a row using loc')
display(df.loc[1])

In [78]:
#Select column by position
print(df)
print('Print of the second colum using iloc')
display(df.iloc[:,1])

   a  b  c
0  1  4  0
1  2  5  0
2  3  6  0
Print of the second colum using iloc


0    4
1    5
2    6
Name: b, dtype: int64

In [79]:
print('Selection of the second row usign iloc')
display(df.iloc[1])

Selection of the second row usign iloc


a    2
b    5
c    0
Name: 1, dtype: int64

Let's focus a little bit on the difference between `loc` and `iloc`:

In [80]:
display(df2)

max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [81]:
display('selection of cobra',df2.loc['cobra'])

'selection of cobra'

max_speed    1
shield       2
Name: cobra, dtype: int64

In [83]:
display('Selection of row and column with loc',df2.loc['cobra','max_speed'])

'Selection of row and column with loc'

1

In [85]:
display('Selection of row and column with iloc',df2.iloc[0,1])

'Selection of row and column with iloc'

2

**NOTE**: In both cases we can use a list to select multiple rows/columns or `:` to select a range

In [86]:
display(df2)
display('Row cobra, all cols',df2.loc['cobra',:])

max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

'Row cobra, all cols'

max_speed    1
shield       2
Name: cobra, dtype: int64

In [87]:
display('Rows cobra and sidewinder, columns max speed',df2.loc[['cobra','sidewinder'],'max_speed'])

'Rows cobra and sidewinder, columns max speed'

cobra         1
sidewinder    7
Name: max_speed, dtype: int64

In [91]:
display(df2)
display('Using iloc',df2.iloc[0:2,0])
#NOTE 0:i i is excluded

max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

'Using iloc'

cobra    1
viper    4
Name: max_speed, dtype: int64

So far the difference between `loc` and `iloc` sesms minimal.

In [92]:
display(df)
display('Selection with loc',df.loc[0])
display('Selection with iloc',df.iloc[0])

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

'Selection with loc'

a    1
b    4
c    0
Name: 0, dtype: int64

'Selection with iloc'

a    1
b    4
c    0
Name: 0, dtype: int64

Can you tell a case when the difference is relevant?

In [93]:
#Change of index
df.index=[1,2,0]
print('df after the change of the index:')
display(df)

df after the change of the index:


a  b  c
1  1  4  0
2  2  5  0
0  3  6  0

In [94]:
display('loc:',df.loc[0],'iloc',df.iloc[0])

'loc:'

a    3
b    6
c    0
Name: 0, dtype: int64

'iloc'

a    1
b    4
c    0
Name: 1, dtype: int64

## Exercise DF

  1. Create a dataframe, `dfEx1` with **2** columns and **3** rows. 
  2. Create a second dataframe, `dfEx2`, with **3** columns and **3** rows.
  3. Select one row from the `dfEx1` using `iloc` and add the values as a new columns in column of `dfEx2`.
  4. Now select two row and two columns in `dfEx2` using `loc` and store the values in a new dataframe.
  
**NOTE** check the type of the results os `iloc` and remember that we can add a column using a `list`.

In [108]:
dfEx1 = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})
dfEx2 = pd.DataFrame({'a':[10,20,30],'b':[40,50,60],'c':[70,80,90]})
dfEx2['new'] = list(dfEx1.iloc[1])
dfEx2.set_index('new',inplace=True)
ret = dfEx2.loc[[2,8],['a','b']]
type(ret)
type(dfEx1.iloc[1])

pandas.core.series.Series

## Warning

If during the selection the dataframes number of columns is __1__ , the type of the object changes from `pd.DataFrame` to `pandas.core.series.Series`. 

This is valid also if you have 2 colum but one __is the index__

In [109]:
print('Original type',type(df2))
print('Only index',type(df2.set_index('max_speed')))
print('Only selection',type(df2.iloc[:,0]))
display(df2.set_index('max_speed').iloc[:,0])
print(type(df2.set_index('max_speed').loc[:,'shield']))

Original type <class 'pandas.core.frame.DataFrame'>
Only index <class 'pandas.core.frame.DataFrame'>
Only selection <class 'pandas.core.series.Series'>


max_speed
1    2
4    5
7    8
Name: shield, dtype: int64

<class 'pandas.core.series.Series'>


## Drop and other suff

After the selction of columns and rows let's focus on how to `drop` a column (aka selct out) from a dataframe.


In [115]:
#Let's drop c from df
df=pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[0,0,0]})
display(df)
df.drop(['c'],axis=1)
display('df after the drop of c',df)

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

'df after the drop of c'

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

Drop is another case in which the use of inplace is very relevant.

In [116]:
df.drop(columns=['b'],inplace=True)
display('df after the drop of b',df)

'df after the drop of b'

a  c
0  1  0
1  2  0
2  3  0

In [117]:
df.columns=['aaa','ccc']
display(df)
#We can also drop rows
df['nomi']=['pippo','pluto','topolino']
display(df)

aaa  ccc
0    1    0
1    2    0
2    3    0

aaa  ccc      nomi
0    1    0     pippo
1    2    0     pluto
2    3    0  topolino

In [118]:
df.set_index(['nomi'],inplace=True)
display('df after the index definitio',df)

'df after the index definitio'

aaa  ccc
nomi              
pippo       1    0
pluto       2    0
topolino    3    0

In [119]:
display('df after the drop of the row with label pluto',df.drop(['pluto'],axis=0))

'df after the drop of the row with label pluto'

aaa  ccc
nomi              
pippo       1    0
topolino    3    0

We have seen how to drop columns and rows, but if we want to drop some values? For example, how we can drop some missing values?

In [120]:
dfNan=pd.DataFrame([[1,np.nan,'pippo'],[2,'b','pluto'],[3,'c','topolino'],[np.nan,np.nan,'minnie'],[np.nan,np.nan,np.nan]])
display(dfNan)

0    1         2
0  1.0  NaN     pippo
1  2.0    b     pluto
2  3.0    c  topolino
3  NaN  NaN    minnie
4  NaN  NaN       NaN

In [121]:
dfNan.dropna()

0  1         2
1  2.0  b     pluto
2  3.0  c  topolino

Can you describe me what is happening in the chunck below?

In [122]:
res2Print={'orig':dfNan,'nothing':dfNan.dropna(),
            'axis=0':dfNan.dropna(axis=0),
            'axis=1':dfNan.dropna(axis=1),
           'how=any':dfNan.dropna(how='any'),
           'how=all':dfNan.dropna(how='all')}

for curConf,curDF in res2Print.items():
    print('dropna with %s'%curConf)
    display(curDF)

dropna with orig


0    1         2
0  1.0  NaN     pippo
1  2.0    b     pluto
2  3.0    c  topolino
3  NaN  NaN    minnie
4  NaN  NaN       NaN

dropna with nothing


0  1         2
1  2.0  b     pluto
2  3.0  c  topolino

dropna with axis=0


0  1         2
1  2.0  b     pluto
2  3.0  c  topolino

dropna with axis=1


Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

dropna with how=any


0  1         2
1  2.0  b     pluto
2  3.0  c  topolino

dropna with how=all


0    1         2
0  1.0  NaN     pippo
1  2.0    b     pluto
2  3.0    c  topolino
3  NaN  NaN    minnie

## Exercise Drop

Create a dataframe like this 

| let | num | col    | fru    |
|-----|-----|--------|--------|
| a   | 1   | red    | apple  |
| b   | 2   | green  | banana |
| c   | 3   | blue   | np.nan |
| d   | 4   | yellow | peach  |

than remove column `num`.

Remove also the row `a`.

Remove the columns with the `nan` value.

What is the type of the dataframe?

In [123]:
import pandas as pd 
import numpy as np
dictDF = {'let':['a','b','c','d'],
         'num':[1,2,3,4],
         'col':['red','green','blue','yellow'],
         'fru':['apple','banana',np.nan,'peach']}
df = pd.DataFrame(dictDF)
display(df)

let  num     col     fru
0   a    1     red   apple
1   b    2   green  banana
2   c    3    blue     NaN
3   d    4  yellow   peach

In [124]:
df.drop(columns=['num'],inplace=True)
df

let     col     fru
0   a     red   apple
1   b   green  banana
2   c    blue     NaN
3   d  yellow   peach

In [125]:
df.set_index('let',inplace=True)
df

col     fru
let                
a       red   apple
b     green  banana
c      blue     NaN
d    yellow   peach

In [126]:
df.drop('a',inplace=True,axis=0)
df

col     fru
let                
b     green  banana
c      blue     NaN
d    yellow   peach

In [127]:
df.dropna(axis=1,inplace=True)
display(df)

col
let        
b     green
c      blue
d    yellow

In [128]:
print(type(df))
type(df.loc[:,'col'])

<class 'pandas.core.frame.DataFrame'>


pandas.core.series.Series

## Join of dataframes

A very handy function to use on dataframe is `join()`.

With join it is possible to combine different dataframe using one column as a key.

This function can be found also in R using `dplyr`.

In [131]:
dfLeft=pd.DataFrame({'key':['a','b','d','f'],'cost':[1,2,3,4]})
dfRight=pd.DataFrame({'key':['a','b','c','f'],'revenue':[10,20,30,40]})
display(dfLeft)
display(dfRight)
display(dfLeft.join(dfRight,lsuffix='_l',rsuffix='_r'))#lsuffix='_l',rsuffix='_r'

key  cost
0   a     1
1   b     2
2   d     3
3   f     4

key  revenue
0   a       10
1   b       20
2   c       30
3   f       40

key_l  cost key_r  revenue
0     a     1     a       10
1     b     2     b       20
2     d     3     c       30
3     f     4     f       40

In [132]:
print('Using index')
dfRight.set_index('key',inplace=True)
display(dfLeft.join(dfRight,on='key'))

Using index


key  cost  revenue
0   a     1     10.0
1   b     2     20.0
2   d     3      NaN
3   f     4     40.0

In [136]:
#ALternative
dfLeft.set_index('key').join(dfRight,how='inner')

cost  revenue
key               
a       1       10
b       2       20
f       4       40

In [135]:
display(dfRight)
display(dfLeft)

revenue
key         
a         10
b         20
c         30
f         40

key  cost
0   a     1
1   b     2
2   d     3
3   f     4

In [134]:
howTypes=['left','right','inner','outer']
d={'how':'','other':dfRight}
for curType in howTypes:
    print('how:{}'.format(curType))
    d['how']=curType
    display(dfLeft.set_index('key').join(**d))

how:left


cost  revenue
key               
a       1     10.0
b       2     20.0
d       3      NaN
f       4     40.0

how:right


cost  revenue
key               
a     1.0       10
b     2.0       20
c     NaN       30
f     4.0       40

how:inner


cost  revenue
key               
a       1       10
b       2       20
f       4       40

how:outer


cost  revenue
key               
a     1.0     10.0
b     2.0     20.0
c     NaN     30.0
d     3.0      NaN
f     4.0     40.0

## Join in R

Just to make a conmparison we are going to make the same join in R.

To do this we'll use the possibility of using a dataframe creted with Pandas in a Python cell inside an R cell.

This is done by `magic` and the command is `%%R -i nameofthePythonDatframe` 

In [137]:
#First we have to remove the index from dfRight
dfRight.reset_index(inplace=True)
#dfLeft.reset_index(inplace=True)

In [138]:
%%R -i dfLeft,dfRight
library(dplyr)
dfLeft %>%
    inner_join(dfRight,by='key')

R[write to console]: 
Attaching package: ‘dplyr’


R[write to console]: The following objects are masked from ‘package:stats’:

    filter, lag


R[write to console]: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




  key cost revenue
1   a    1      10
2   b    2      20
3   f    4      40


## End Exercise #1

You have to:

  - Create an `np.array` with __3__ columns and **4** rows and transform it in an `pd.dataFrame`. Value and column's names must be like the table below  
  - Create a first datafreme with columns **key** and **col1** and the **first** 3 rows
  - Create a first datafreme with columns **key** and **col2** and the **last** 3 rows
  - Join the two dataframes on key in **inner** mode
  - Drop one column of the result dataframe
  
| key | col1 | col2 |
|---|:-:|----|
| a | 1 | 10 |
| b | 2 | 20 |
| c | 3 | 30 |
| b | 4 | 40 |
| c | 5 | 50 |
| d | 6 | 60 |

## Real-life example

Reading a CSV file can be tricky some times.

In [141]:
exPath = '/Users/msaletta/workingDir/Code/didattica_interna/garanzieAdd/data/fullData_5000.csv'

dfRead = pd.read_csv(exPath,sep=',', keep_default_na=False, na_values=[np.nan, ''],dtype={'cap':str})
dfRead.head()

ID                        day ASF_proprietario_is_conducente sesso  \
0  318091613  2018-10-06 00:00:00+00:00                              S     M   
1  317149604  2018-09-15 00:00:00+00:00                              S     M   
2  317348124  2018-09-19 00:00:00+00:00                              S     F   
3  318707117  2018-10-22 00:00:00+00:00                              S     M   
4  318707117  2018-10-22 00:00:00+00:00                              S     M   

  datanascita provincianascita provincia    cap ASF_domicilio_is_residenza  \
0  1987-10-07               SN        MI  20025                          S   
1  1937-05-20               RM        RM  00163                          S   
2  1990-02-23               MT        LO  26815                          S   
3  1981-04-15               TP        TP  91026                          S   
4  1981-04-15               TP        TP  91026                          S   

   statocivile  ... traino         assicurazione sinistri_senzacolpa  \
0            7  ...      S                   NaN                 0.0   
1            6  ...      N         Nuova Tirrena                 2.0   
2            1  ...      N               Zuritel                 0.0   
3            1  ...      N  Aurora Assicurazioni                 0.0   
4            1  ...      N  Aurora Assicurazioni                 0.0   

  sinistri_princ  sinistri_parit classe ASF_metodo_pagamento  \
0            0.0             0.0     12                    1   
1            0.0             0.0      9                    1   
2            0.0             0.0     1X                    1   
3            0.0             0.0     1X                    1   
4            0.0             0.0     1X                    1   

  ASF_eta_conducente_minore ASF_eta_patentato_minore garanzie  
0                      30.0                       26      193  
1                       NaN                       22        1  
2                      25.0                       25        1  
3                      30.0                       26     4097  
4                      30.0                       26        1  

[5 rows x 43 columns]

In [142]:
setProv = set(dfRead.provincia)
'NA' in setProv

True