Introduction to Python
================================

Lesson 2 - Part1
--------

## Summary

In this Lesson we will start using Python in order to create some models.

The models that we will create are:
  - Linear

In order to do so we must intruduce some important libraries:

  - Pandas
  - Sklearn
  - Numpy

In [97]:
%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


## Numpy

Citing from the [Numpy Website](http://www.numpy.org/) :NumPy is the fundamental package for scientific computing with Python. It contains among other things:
  - a powerful N-dimensional array object
  - sophisticated (broadcasting) functions
  - tools for integrating C/C++ and Fortran code
  - useful linear algebra, Fourier transform, and random number capabilities
For the moment our focus is on the first point, in oder to start usign proper arrays.

In [3]:
import numpy as np
#Creation of an array
ar1=np.array([1,2,3])
print('type di ar1',type(ar1))
ar1

type di ar1 <class 'numpy.ndarray'>


array([1, 2, 3])

Note the difference between this new object and the standard Python list:

In [3]:
classList = [1,2,3]
print('Type of classList:',type(classList))
print(ar1,classList)

Type of classList: <class 'list'>
[1 2 3] [1, 2, 3]


In [4]:
#Use shape to see the dimension of ar1
print('Dimension of ar1 are:',ar1.shape)
try:
    print('Using .shape()')
    print(ar1,ar1.shape())
except Exception as e:
    print('ERROR:',e)
    print('You must use .shape without brackets')
    print(ar1,ar1.shape)

Dimension of ar1 are: (3,)
Using .shape()
ERROR: 'tuple' object is not callable
You must use .shape without brackets
[1 2 3] (3,)


Why we have to use `shape`? We can't use `len`?

In [6]:
len(ar1)

3

In [6]:
#Creation of a multimensional array
ar2=np.array([[1,2,3],[4,5,6]])#,dtype=complex
print('Shape di ar2',ar2.shape)
print(ar2)
len(ar2)

Shape di ar2 (2, 3)
[[1 2 3]
 [4 5 6]]


2

## Comparison with R array

Numpy array are very similar to `R` array:

In [13]:
%%R

arR1 = array(c(1,2,3,4,5,6),c(2,3))
arR1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


**NOTE**: array and matrix in nupy are different objects

In [ ]:
#Creatiomn of a matrix
mt=np.mat('1 2;3 4')
print(type(mt))
print(mt)
#Putting the matrix inside an array
ar3=np.array([np.mat('1 2; 3 4'),np.mat('4 5; 6 7')])
print(type(ar3))
print(ar3)
#In order to keep the correct type
ar3=np.array(np.mat('1 2; 3 4'), subok=True)
print(type(ar3))
print(ar3)
#ar3
# mt

How do I select elements inside an array?

In [21]:
#The same way we do with list
print(ar2[1])
print(type(ar2[1]))
#To access a singl element
ar2[1,2]

[4 5 6]
<class 'numpy.ndarray'>


6

**NOTE**: as we have seen in the previos lesson, also with `np.array` we have to use `.copy()`.

Without `.copy()` we'll create a pointer to the original array.

In [23]:
print(ar2)
ar2_bis=ar2#.copy()
ar2_bis[1,]=[1,1,1]
#What'll be the result of this operation?
##print(ar2)
#ar2_bis

[[1 2 3]
 [1 1 1]]
[[1 2 3]
 [1 1 1]]


## Other properties of np.array

Just to mention some other features, we can look to append:

In [24]:
ap1=np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])
print(ap1,type(ap1))
#Please note that the result is flattened
ap2=np.append([[1, 2, 3]], [[4, 5, 6], [7, 8, 9]], axis=0)
print(ap2,type(ap2))
ap3=np.append([[1, 2, 3],[1,1,1]], [[4, 5, 6], [7, 8, 9]], axis=1)
print(ap3,type(ap3))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[[1 2 3 4 5 6]
 [1 1 1 7 8 9]] <class 'numpy.ndarray'>


## Comparison between array an list

Let's understand why for big data it's important to use an array istead of a list.

We are going to do the sum of the list and two array. In one case is the sum of number, in the other the sum between two arrays like in linear algebra.

In [25]:
a=[i for i in range(0,10000)]
%timeit -n 100 s=a+a
b=np.array([i for i in range(0,10000)])
%timeit -n 100 s2=b+b

72.2 µs ± 5.19 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
The slowest run took 4.04 times longer than the fastest. This could mean that an intermediate result is being cached.
6.64 µs ± 4.38 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
%%R
c=as.integer(seq(1,10))
print(class(c))
d=data.frame(c)
print(class(d))


[1] "integer"
[1] "data.frame"


In [27]:
%%timeit -n 100
%R c+c

1.32 ms ± 168 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
%%timeit -n 100
%R d+d

/Users/msaletta/anaconda3/envs/Cattolica/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py:191: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  res = PandasDataFrame.from_items(items)


2.08 ms ± 160 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Pandas 

Citing the [Pandas Website](https://pandas.pydata.org/): *pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language*.

What interest us the most is the possibility of create and use, like in R, **dataframes** ([Pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)).

In [76]:
import pandas as pd

#Creation of a dataframe
df=pd.DataFrame({'a':[1,2,3],'b':[4,5,6]})
print(df,'\n',type(df))

   a  b
0  1  4
1  2  5
2  3  6 
 <class 'pandas.core.frame.DataFrame'>


Remembering previous lessons, can you tell what we have just done?
How can We generalize the previous expression?

In [98]:
#We can create a dataframe also using another syntax
df1_bis = pd.DataFrame([[10,20,30],[11,21,31]],columns=['ten','twenty','thirty'])
print(df1_bis)
print('We can add columns afterward')
df['c']=[0,0,0]
print(df)
#Creatiion of a dataframe with index
df2 = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
                  index=['cobra', 'viper', 'sidewinder'],
                  columns=['max_speed', 'shield'])
print(df2)
print(type(df2))
df3=pd.DataFrame({'col1':[10,20,30],'col2':['y','z','k']},index=['a','b','c'])
df3

   ten  twenty  thirty
0   10      20      30
1   11      21      31
We can add columns afterward
   a  b  c   d
0  1  4  0 NaN
1  2  5  0 NaN
2  3  6  0 NaN
            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
<class 'pandas.core.frame.DataFrame'>


col1 col2
a    10    y
b    20    z
c    30    k

**NOTE**: a dataframe can be created also starting from a `np.array` simply using `pd.DataFrame`.

In [33]:
dfFromArray=pd.DataFrame(ap2)#,columns=['pippo','pluto','paperino'])
print(ap2)
dfFromArray


[[1 2 3]
 [4 5 6]
 [7 8 9]]


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Properties of a dataframe

In the followig cell there is a sample of attributes ad properties of a pandas dataframe.

Some of them are:

  - `index`
  - `values`
  - `max()`
  - `add()`

In [34]:
%qtconsole
print(df)
df.index
df.values
df.columns
df.max()
df.min()
df.mean()
df.median()
df.add(df)
#se the link above

   a  b  c
0  1  4  0
1  2  5  0
2  3  6  0


TypeError: 'Index' object is not callable

## Display dataframes nicely

In order to print a dataframe in a nice way, like it is visualized without print if it is at the of a cell, we can use `display` from the library `IPython.display`.

It is also possible to convert a dataframe to html with `to_html`, from the same library, and then use display.

**NOTE**: display can also print text before and after an object, just like `print`.

In [46]:
from IPython.display import display, HTML
display(df)
#Alternative
print('using .to_html()')
display(HTML(df.to_html()))
print('Display can also print text')
display('Some random text',df)

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

using .to_html()


Display can also print text


'Some random text'

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

## How to select row and columns

Let's dive a little bit more in some dataframes property.

Important functions for selecting dataframe's elements are:
  - `index` 
  - `loc`
  - `iloc`
 
The difference between `loc` and `iloc` is subtle:
  - `loc` allow to select elemets by **name**
  - `iloc` allow to select elemets by **position**

It always possible to select columns by name with `[[]]`.

In [51]:
#Creation of a dataframe without an index
dfCity=pd.DataFrame({'val1':[10,20,30],'val2':[-1,-2,-3],'city':['Roma','Milano','Napoli']})
print('dfCity before the cration of the index')
display(dfCity)
#Selecting one column as index
dfCity.set_index('city')#inplace
display(dfCity)

dfCity before the cration of the index


val1  val2    city
0    10    -1    Roma
1    20    -2  Milano
2    30    -3  Napoli

val1  val2    city
0    10    -1    Roma
1    20    -2  Milano
2    30    -3  Napoli

### WARNING #1
From now on, we must take care on the parameter `inplace` when we use multiple functions over a dataframe

In [59]:
#Selecting column by name
display(df)
print('Selection of a column by name')
display(df[['a']])
print('Selectig a column using loc')
display(df.loc[:,'a'])
print('Selectig a row using loc')
display(df.loc[1])
#Select column by position
print('Print of the second colum using iloc')
display(df.iloc[:,1])
print('Selection of the second row usign iloc')
display(df.iloc[1])

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

Selection of a column by name


a
0  1
1  2
2  3

Selectig a column using loc


0    1
1    2
2    3
Name: a, dtype: int64

Selectig a row using loc


a    2
b    5
c    0
Name: 1, dtype: int64

Print of the second colum using iloc


0    4
1    5
2    6
Name: b, dtype: int64

Selection of the second row usign iloc


a    2
b    5
c    0
Name: 1, dtype: int64

Let's focus a little bit on the difference between `loc` and `iloc`:

In [26]:
display(df2)
display('selection of cobra',df2.loc['cobra'])
display('Selection of row and column with loc',df2.loc['cobra','max_speed'])
display('Selection of row and column with iloc',df2.iloc[0,0])

'selection of cobra'

max_speed    1
shield       2
Name: cobra, dtype: int64

'Selection of row and column with loc'

1

'Selection of row and column with iloc'

1

**NOTE**: In both cases we can use a list to select multiple rows/columns or `:` to select a range

In [95]:
display(df2)
display('Row cobra, all cols',df2.loc['cobra',:])
display('Rows cobra and sidewinder, columns max speed',df2.loc[['cobra','sidewinder'],'max_speed'])
display('Using iloc',df2.iloc[0:2,0])
#NOTE 0:i i is excluded

max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

'Row cobra, all cols'

max_speed    1
shield       2
Name: cobra, dtype: int64

'Rows cobra and sidewinder, columns max speed'

cobra         1
sidewinder    7
Name: max_speed, dtype: int64

'Using iloc'

cobra    1
viper    4
Name: max_speed, dtype: int64

So far the difference between `loc` and `iloc` sesms minimal.

In [ ]:
display(df)
display('Selection with loc',df.loc[0])
display('Selection with iloc',df.iloc[0])

Can you tell a case when the difference is relevant?

In [61]:
#Change of index
df.index=[1,2,0]
print('df after the change of the index:')
display(df)
display('loc:',df.loc[0],'iloc',df.iloc[0])

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

'Selection with loc'

a    1
b    4
c    0
Name: 0, dtype: int64

'Selection with iloc'

a    1
b    4
c    0
Name: 0, dtype: int64

df after the change of the index:


a  b  c
1  1  4  0
2  2  5  0
0  3  6  0

'loc:'

a    3
b    6
c    0
Name: 0, dtype: int64

'iloc'

a    1
b    4
c    0
Name: 1, dtype: int64

## Exercise DF

  1. Create a dataframe, `dfEx1` with **2** columns and **3** rows. 
  2. Create a second dataframe, `dfEx2`, with **3** columns and **3** rows.
  3. Select one row from the `dfEx1` using `iloc` and add the values as a new columns in column of `dfEx2`.
  4. Now select two row and two columns in `dfEx2` using `loc` and store the values in a new dataframe.
  
**NOTE** check the type of the results os `iloc` and remember that we can add a column using a `list`.

a   b   c  new
a  10  40  70    2
b  20  50  80    5
c  30  60  90    8

b  new
a  40    2
c  60    8

## Warning

If during the selection the dataframes number of columns is **1**, the type of the object changes from `pd.DataFrame` to `pandas.core.series.Series`. 
This is valid also if you have 2 colum but one **is the index**.

In [104]:
print('Original type',type(df2))
print('Only index',type(df2.set_index('max_speed')))
print('Only selection',type(df2.iloc[:,0]))
display(df2.set_index('max_speed').iloc[:,0])
print(type(df2.set_index('max_speed').loc[:,'shield']))

Original type <class 'pandas.core.frame.DataFrame'>
Only index <class 'pandas.core.frame.DataFrame'>
Only selection <class 'pandas.core.series.Series'>


max_speed
1    2
4    5
7    8
Name: shield, dtype: int64

<class 'pandas.core.series.Series'>


## Drop and other suff

After the selction of columns and rows let's focus on how to `drop` a column (aka selct out) from a dataframe.


In [105]:
#Let's drop c from df
df=pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[0,0,0]})
df.drop(['c'],axis=1)
display('df after the drop of c',df)

'df after the drop of c'

a  b  c
0  1  4  0
1  2  5  0
2  3  6  0

Drop is another case in which the use of drop is very relevant.

In [107]:
df.drop(columns=['b'],inplace=True)
display('df after the drop of b',df)

'df after the drop of b'

a  c
0  1  0
1  2  0
2  3  0

In [109]:
df.columns=['aaa','ccc']
display(df)
#We can also drop rows
df['nomi']=['pippo','pluto','topolino']
df.set_index(['nomi'],inplace=True)
display('df after the index definitio',df)
display('df after the drop of the row with label pluto',df.drop(['pluto'],axis=0))

aaa  ccc
nomi              
pippo       1    0
pluto       2    0
topolino    3    0

'df after the index definitio'

aaa  ccc
nomi              
pippo       1    0
pluto       2    0
topolino    3    0

'df after the drop of the row with label pluto'

aaa  ccc
nomi              
pippo       1    0
topolino    3    0

We have seen how to drop columns and rows, but if we want to drop some values? For example, how we can drop some missing values?

In [113]:
dfNan=pd.DataFrame([[1,np.nan,'pippo'],[2,'b','pluto'],[3,'c','topolino'],[np.nan,np.nan,'minnie'],[np.nan,np.nan,np.nan]])
display(dfNan)
dfNan.dropna()

0    1         2
0  1.0  NaN     pippo
1  2.0    b     pluto
2  3.0    c  topolino
3  NaN  NaN    minnie
4  NaN  NaN       NaN

0  1         2
1  2.0  b     pluto
2  3.0  c  topolino

Can you describe me what is happening in the chunck below?

In [114]:
res2Print={'orig':dfNan,'nothing':dfNan.dropna(),
            'axis=0':dfNan.dropna(axis=0),
            'axis=1':dfNan.dropna(axis=1),
           'how=any':dfNan.dropna(how='any'),
           'how=all':dfNan.dropna(how='all')}
for curConf,curDF in res2Print.items():
    print('dropna with %s'%curConf)
    display(curDF)

dropna with orig


0    1         2
0  1.0  NaN     pippo
1  2.0    b     pluto
2  3.0    c  topolino
3  NaN  NaN    minnie
4  NaN  NaN       NaN

dropna with nothing


0  1         2
1  2.0  b     pluto
2  3.0  c  topolino

dropna with axis=0


0  1         2
1  2.0  b     pluto
2  3.0  c  topolino

dropna with axis=1


Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

dropna with how=any


0  1         2
1  2.0  b     pluto
2  3.0  c  topolino

dropna with how=all


0    1         2
0  1.0  NaN     pippo
1  2.0    b     pluto
2  3.0    c  topolino
3  NaN  NaN    minnie

## Exercise Drop

Create a dataframe like this 

| let | num | col    | fru    |
|-----|-----|--------|--------|
| a   | 1   | red    | apple  |
| b   | 2   | green  | banana |
| c   | 3   | blue   | np.nan |
| d   | 4   | yellow | peach  |

than remove column `num`.

Remove also the row `a`.

Remove the columns with the `nan` value.

What is the type of the dataframe?

## Join of dataframes

A very handy function to use on dataframe is `join()`.

With join it is possible to combine different dataframe using one column as a key.

This function can be found also in R using `dplyr`.

In [127]:
dfLeft=pd.DataFrame({'key':['a','b','d','f'],'cost':[1,2,3,4]})
dfRight=pd.DataFrame({'key':['a','b','c','f'],'revenue':[10,20,30,40]})
display(dfLeft.join(dfRight,lsuffix='_l',rsuffix='_r'))#lsuffix='_l',rsuffix='_r'
print('Using index')
dfRight.set_index('key',inplace=True)
display(dfLeft.join(dfRight,on='key'))
#ALternative
dfLeft.set_index('key').join(dfRight)#how
howTypes=['left','right','inner','outer']
d={'how':'','other':dfRight}
for curType in howTypes:
    print('how:{}'.format(curType))
    d['how']=curType
    display(dfLeft.set_index('key').join(**d))

key_l  cost key_r  revenue
0     a     1     a       10
1     b     2     b       20
2     d     3     c       30
3     f     4     f       40

Using index


key  cost  revenue
0   a     1     10.0
1   b     2     20.0
2   d     3      NaN
3   f     4     40.0

how:left


cost  revenue
key               
a       1     10.0
b       2     20.0
d       3      NaN
f       4     40.0

how:right


cost  revenue
key               
a     1.0       10
b     2.0       20
c     NaN       30
f     4.0       40

how:inner


cost  revenue
key               
a       1       10
b       2       20
f       4       40

how:outer


cost  revenue
key               
a     1.0     10.0
b     2.0     20.0
c     NaN     30.0
d     3.0      NaN
f     4.0     40.0

## Join in R

Just to make a conmparison we are going to make the same join in R.

To do this we'll use the possibility of using a dataframe creted with Pandas in a Python cell inside an R cell.

This is done by `magic` and the command is `%%R -i nameofthePythonDatframe` 

In [128]:
#First we have to remove the index from dfRight
dfRight.reset_index(inplace=True)
#dfLeft.reset_index(inplace=True)

In [129]:
%%R -i dfLeft,dfRight
library(dplyr)
dfLeft %>%
    inner_join(dfRight,by='key')

  key cost revenue
1   a    1      10
2   b    2      20
3   f    4      40


## End Exercise #1

You have to:

  - Create an `np.array` with __3__ columns and **4** rows and transform it in an `pd.dataFrame`. Value and column's names must be like the table below  
  - Create a first datafreme with columns **key** and **col1** and the **first** 3 rows
  - Create a first datafreme with columns **key** and **col2** and the **last** 3 rows
  - Join the two dataframes on key in **inner** mode
  - Drop one column of the result dataframe
  
| key | col1 | col2 |
|---|:-:|----|
| a | 1 | 10 |
| b | 2 | 20 |
| c | 3 | 30 |
| b | 4 | 40 |
| c | 5 | 50 |
| d | 6 | 60 |

k c1
0  a  1
1  b  2
2  c  3

k  c2
3  b  40
4  c  50
5  d  60

c1
k   
b  2
c  3